# ==========================================
# 站点基本资料（✅ 可自由改动）
# ==========================================
title: "Sephoration 的知识库"          # 浏览器标签+左上角大字
description: "用 Jekyll 搭的文档站"     # SEO 描述，一句话即可
baseurl: ""                            # 🚫 别动！GitHub Pages 根目录已是最顶层
url: "https://sephoration.github.io"   # 🚫 别动！GitHub Pages 强制这个域名

# 下面三项跟「编辑此页」按钮有关，用不到就留空
repository: "Sephoration/Sephoration.github.io"
gh_edit_repository: "https://github.com/Sephoration/Sephoration.github.io"
gh_edit_branch: "main"

# ==========================================
# 外观功能（✅ 可自由改动）
# ==========================================
logo: ""                    # 填 /assets/images/xxx.png 即可换左上角图标
color_scheme: nil           # 可选 nil / dark / light 或自己写配色文件
search_enabled: true        # 是否开启搜索
heading_anchors: true       # 标题是否带锚点
back_to_top: true           # 右下角「回到顶部」按钮
enable_copy_code_button: true  # 代码块一键复制

# 顶部右侧「外链」按钮（✅ 可自由改动）
aux_links:
  "我的博客":
    - "https://sephoration.github.io"

# ==========================================
# 以下全是技术配置（🚫 不建议动，除非你知道后果）
# ==========================================
permalink: pretty
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-sitemap

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

sass:
  quiet_deps: true
  silence_deprecations: ['import']

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# ==========================================
# 导航/目录/提示块等高级功能（✅ 可自由改动）
# ==========================================
nav_enabled: true
toc_enabled: true
callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: 重要
    color: blue
  new:
    title: 新增
    color: green
  note:
    title: 备注
    color: purple
  warning:
    title: 警告
    color: red

# ==========================================
# 以下默认即可，不用管（🚫 别动）
# ==========================================
liquid:
  error_mode: strict
  strict_filters: true
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - LICENSE.txt
  - package*.json
  - Rakefile
  - README.md
  - CODE_OF_CONDUCT.md
  - docker-compose.yml
  - Dockerfile
  - fixtures/