#欢迎来到 Jekyll！
#此配置文件用于设定影响整个站点的参数，这些值通常一次性设置，之后很少改动。
#如果你发现自己经常编辑本文件，请考虑使用 Jekyll 的“数据文件”功能来存放需要频繁更新的数据。
#由于技术原因，使用 jekyll serve 时不会自动重载本文件。
#若修改了此处内容，请重新启动服务器进程。

#站点设置
#以下字段用于个性化你的新站点。在 HTML 模板中，你会看到它们通过 {{ site.title }}、{{ site.github_repo }} 等方式被调用。
#你也可以创建任何自定义变量，例如 {{ site.myvariable }}，即可在模板中随处使用。

theme: just-the-docs
title: 阿四的小网站
description: 计算机的学习记录  #搜索显示名字
baseurl: ""      #若部署到子目录需写
url: "https://github.com/Sephoration" # the base hostname & protocol for your site, e.g. http://example.com
repository: https://github.com/Sephoration/Sephoration.github.io # for github-metadata

permalink: pretty

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "minimal"



# 站点 Logo
# 如需显示图片 Logo（而非文字标题），去掉注释并填写路径
# logo: /assets/images/2 (3).jpg


# ================================================================
# 搜索设置
# ================================================================
# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: "k"




# 代码块右上角「复制」按钮
enable_copy_code_button: true

# By default, consuming the theme as a gem leaves mermaid disabled; it is opt-in

  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/

  # Put any additional configuration, such as setting the theme, in _includes/mermaid_config.js
  # See also docs/ui-components/code
  # To load mermaid from a local library, also use the `path` key to specify the location of the library; e.g.
  # for (v10+):
  # path: "/assets/js/mermaid.esm.min.mjs"
  # for (<v10):
  # path: "/assets/js/mermaid.min.js"
  # Note: copy both `mermaid.esm.min.mjs` (v10+) or `mermaid.min.js` (<v10) and the associated `.map` file from the specified version of `mermaid/dist` to `/assets/js/`.

#标题锚点，h1-h6 左侧出现可点击的符号
heading_anchors: true


# ===== 右上角辅助链接 =====
aux_links:
  "GitHub 主页":
    - "https://github.com/Sephoration"


aux_links_new_tab: false  #是否在新标签页打开辅助链接

nav_enabled: true  # 侧边栏/移动端导航总开关

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase# 大写字母排在小写前面；用 case_insensitive 忽略大小写

# External navigation links # 底部「外部导航」链接（出现在侧边栏最下方）
nav_external_links:
  - title: Just the Docs on GitHub
    url: https://github.com/just-the-docs/just-the-docs

# Show navigation error report
nav_error_report: true # default is false/nil.
# 导航错误报告（找不到页面时给出提示）# 开发阶段打开，上线后可 false


# Liquid 引擎严格模式（开发时开启，提前暴露变量/过滤器错误）
liquid:
  error_mode: strict
  strict_filters: true



# ================================================================
# 页脚内容（每页主体底部出现）
# ================================================================
# footer_content 可写任意 HTML，留空则不显示额外文字
back_to_top: true
back_to_top_text: "回到顶部"
footer_content: '一一得一，十十得百，百百千千，千千万万。——《增广贤文》'
# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/Sephoration/Sephoration.github.io" # the repository that your docs are stored in
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately




# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil


callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red




# ================================================================
# 目录 ToC [true or false]
# ================================================================
toc_enabled: true          # 启用或禁用目录侧边/顶部面板
toc:
  min_heading_level: 1     # 纳入目录的标题级别，默认2【1=<h1>，2=<h2>……】
  max_heading_level: 6
  ordered: false           # 目录用有序列表（true）还是无序列表（false）
  flat_toc: false          # 是否把目录压扁成单级列表，true=单级，false=保留层级缩进
  highlight_active: true   # 是否在目录中高亮当前可视区域章节（需 JavaScript）
  highlight:
    in_view: true          # true=高亮所有在视口内的章节；false=仅高亮第一个 
    offset: 60             # 判定章节“进入视口”时距离顶部的像素偏移，留空则取视口正中
  # 目录面板样式：side=固定侧边，float=浮动可关闭（默认），设为 float 时，双击侧边栏开关按钮可回到顶部
  # 'float' 或 'side'，此外还可以给面板添加任意自定义 CSS 类名，多个类名用空格分隔。
  style: "float"          
  title: "这是一个目录呀~"  # 目录面板标题，会显示在目录上方及移动端横幅
  back_to_top: true        # 目录面板里是否显示“回到顶部”按钮，默认 true
  gh_edit_link: false      # 目录面板里是否显示“在 GitHub 编辑此页”链接（需先配置 gh_edit_link）
  # 跳过到目录面板的辅助功能链接文字（需 JavaScript）
  # skip_label: "Skip to the Table of Contents"
  # 快速打开目录面板的快捷键（需 JavaScript），默认 t；删除整行则禁用
  shortcut:
    key: "t" # or any other key you prefer, remove this option to set 't' as the default
    # ctrl_meta: false # or true => press and hold Ctrl on Windows/Linux or Command on macOS + key to open the ToC panel
    # alt: false # or true => press and hold Alt on Windows/Linux or Option on macOS + key to open the ToC panel
    # shift: false # or true => press and hold Shift + key to open the ToC panel
    # 如需更多 jekyll-toc 设置，见 _includes/vendor/toc.html



# ================================================================
# 谷歌分析跟踪（可选），用于网站流量统计
# ================================================================
# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
# Note: the main Just the Docs site does *not* use Google Analytics.
# ga_tracking: UA-2709176-10,G-5FG1HLH3XQ
# ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)



# ================================================================
# 优化设置
# ================================================================
plugins:
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-sitemap

kramdown:                         #Jekyll 默认用 kramdown 解析 Markdown
  syntax_highlighter_opts:        #控制代码块高亮
    block:
      line_numbers: false         #代码块不显示行号 false/true

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all

sass:
  quiet_deps: true # https://github.com/just-the-docs/just-the-docs/issues/1541
  silence_deprecations: ['import'] # https://github.com/just-the-docs/just-the-docs/issues/1607

exclude:
  # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # specific to the theme website:
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - LICENSE.txt
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - CODE_OF_CONDUCT.md
  - docker-compose.yml
  - Dockerfile
  # theme test code
  - fixtures/